# Generated by Django 4.0.4 on 2022-05-18 01:08

from django.db import migrations, models
import shipping.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resi', models.CharField(default=shipping.utils.create_new_ref_number, editable=False, max_length=10, unique=True)),
                ('nama_barang', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=255)),
                ('nama_pengirim', models.CharField(max_length=50)),
                ('alamat_pengirim', models.TextField(null=True)),
                ('nama_penerima', models.CharField(max_length=50)),
                ('alamat_penerima', models.TextField(null=True)),
                ('berat', models.IntegerField()),
                ('tarif_per_kilo', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Shipping',
            },
        ),
        migrations.CreateModel(
            name='TarifPerKilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tarif per Kilo',
            },
        ),
    ]
